#!/usr/bin/env bash

rm -rf dist

# Process javascript
$(npm bin)/babel -d dist/src src
$(npm bin)/babel -d dist/addons addons

cp readme.md dist/readme.md
cp LICENSE.md dist/LICENSE.md
cp -r docs dist/docs
cp -r style dist/style

node-sass ./style/colonel.scss --stdout > dist/colonel-kurtz.css

# Rewrite the package.json for for the distribution folder
node -p 'p=require("./package");p.main="src/Colonel.js";p.scripts=p.devDependencies=undefined;JSON.stringify(p,null,2)' > dist/package.json

# Remove tests
find -X dist -type d -name __tests__ | xargs rm -rf
